package com.epicx.apps.dailyconsumptionformapp

object FormConstants {
    val vehicleList = listOf(
        "BNA 07", "BNA 08", "BNA 09", "BNA 10", "BNA 11", "BNA 17", "BNA 21", "BNA 22",
        "BNA 25", "BNA 26", "BNA 29","RS-01"
    ) + (1..50).map { n -> "BNB %02d".format(n) }

    val medicineList = listOf(
        "Tab. Paracetamol 500 mg",
        "Inj. Paracetamol 60 mg (Water based)",
        "Tab. Asprin 300 mg",
        "Tab. Angised 0.5 mg",
        "Inj. Adrenaline in Pre-filled Syringe",
        "Inj. Hydrocortisone (250 mg)",
        "Inj. Pheniramine Maleate (25 mg)",
        "Ipratropium Bromide (20 ml)",
        "Inj. Dimenhydrinate (50 mg / ml)",
        "Inj. 25% Dextrose Water (20 ml)",
        "Inj. Diazepam 10 mg",
        "Tab. Captopril 25 mg",
        "Inj. Ringer Lactate (500 ml)",
        "Inj. Normal Saline (500/1000 ml)",
        "Inj. Diclofenac sodium water based (75 mg / 3ml)",
        "Povi-iodine Solution 10% (450 ml)",
        "Polymyxin B Sulphate Skin Ointment with lignocaine (20 gm)",
        "Lignocaine gel 2% (15 gm)",
        "Surface Disinfectant Spray",
        "Ethyl Chloride Spray (175 ml)",
        "Silver Sulphadiazine Cream (50gm)",
        "Airway 0",
        "Airway 1",
        "Airway 2",
        "Airway 3",
        "Airway 4",
        "Airway 5",
        "Laryngeal Mask Airway (LMA) 02",
        "Laryngeal Mask Airway (LMA) 03",
        "Laryngeal Mask Airway (LMA) 04",
        "Alcohol Swabs",
        "Disposable Syringes 05 ml",
        "Disposable 20 ml",
        "IV Cannula 18 No",
        "IV Cannula 20 No",
        "IV Cannula 22 No",
        "IV Cannula 24 No",
        "Drip Set",
        "Intraosseous Needle",
        "Cotton Bandages BPC 6.5 cm X 6 meter (2.5 inch)",
        "Cotton Bandages BPC 10 cm X 6 meter (4 inch)",
        "Cotton Bandages BPC 15 cm X 6 meter",
        "Crape Bandage Size 04 inches x 4.5 meter",
        "Sterilized Gauze Pieces 10 cm x 10 cm 1 box",
        "Paper Adhesive Tape (1”)",
        "Cotton Roll (500 gm)",
        "Nelton Catheter (18 Gauge)",
        "Nebulizer Mask with tubing (Small)",
        "Nebulizer Mask with tubing (Large)",
        "Adjustable Hard Cervical Collar with chin Support",
        "Triangular Bandage (Medium)",
        "Triangular Bandage (Large)",
        "Compatible Lancets",
        "Glucometer Active",
        "Glucometer Strips Accu-Check Active",
        "Glucometer Strips Accu-Check Instant",
        "Glucometer Strips Accu-Check Performa",
        "Glucometer Strips Medisign",
        "Neomycin Sulphate 0.5%, bacitracin zinc",
        "Examination Gloves"
    )

    val monthlyOrderConsumptionList = listOf(
        "Alcohol Swabs", "Burn Cream","Adjustable Hard Cervical Collar with chin Support", "Compatible Lancets","Cotton Bandages BPC 10 cm X 6 meter (4 inch)",
        "Cotton Bandages BPC 15 cm X 6 meter","Cotton Bandages BPC 6.5 cm X 6 meter (2.5 inch)","Cotton Roll (500 gm)","Crape Bandage Size 04 inches x 4.5 meter",
        "Disposable 20 ml","Examination Gloves","Disposable Syringes 05 ml","Drip Set","Glucometer Strips Accu-Check Active","Glucometer Strips Accu-Check Instant",
        "Glucometer Strips Accu-Check Performa","Glucometer Strips Medisign","Inj. 25% Dextrose Water (20 ml)","Inj. Diclofenac sodium water based (75 mg / 3ml)",
        "Inj. Dimenhydrinate (50 mg / ml)","Inj. Hydrocortisone (250 mg)","Inj. Normal Saline (500/1000 ml)","Inj. Ringer Lactate (500 ml)","Ipratropium Bromide (20 ml)",
        "IV Cannula 18 No", "IV Cannula 20 No", "IV Cannula 22 No", "IV Cannula 24 No","Lignocaine gel 2% (15 gm)","Nebulizer Mask with tubing (Large)","Neomycin Sulphate 0.5%, bacitracin zinc",
        "Paper Adhesive Tape (1”)","Polymyxin B Sulphate Skin Ointment with lignocaine (20 gm)","Povi-iodine Solution 10% (450 ml)","Silver Sulphadiazine Cream (50gm)",
        "Sterilized Gauze Pieces 10 cm x 10 cm 1 box","Tab. Angised 0.5 mg","Tab. Captopril 25 mg","Tab. Paracetamol 500 mg","Paper Ream","Expense Register","Vehicle Log Book Fuel for vehicle meter reading",
        "Stock Register", "Dispatch Register", "Diary Register", "File Cover A4", "Indent Book for Store", "Emergency Medical Kit Bags for Rescue Posts (RP’s)", "Emergency Backpack",
        "Dead Body Sheets", "Wooden Splints (Small 3\"x18)", "Wooden Splints (Medium 3\"x36\")", "Rescue Working Gloves 10\"", "Alcohol Swab (200 No/Box)", "Duster Cloth", "Detergent powder (1 Kg) pack",
        "Hand Wash Soap", "Surface cleaner", "AFFF"
    )
    val monthlySskList = listOf(
        "Alcohol Swabs",
        "Burn Cream",
        "Cervical Collar with chin Support",
        "Compatible Lancets",
        "Cotton Bandages BPC 10 cm X 6 meter",
        "Cotton Bandages BPC 15 cm X 6 meter",
        "Cotton Bandages BPC 6.5 cm X 6 meter",
        "Cotton Roll (500 gm)",
        "Crape Bandage Size 04 inches x 4.5 meter",
        "Disposable 20 ml",
        "Disposable Latex Gloves (in pairs)",
        "Disposable Syringes 05 ml",
        "Drip Set",
        "Glucometer Strips Accu-Check Active",
        "Glucometer Strips Accu-Check Instant",
        "Glucometer Strips Accu-Check Performa",
        "Glucometer Strips Medisign",
        "Inj. 25% Dextrose Water (20 ml)",
        "Inj. Diclofenac sodium water based (75mg / 3ml)",
        "Inj. Dimenhydrinate (50 mg / ml)",
        "Inj. Hydrocortisone (250 mg)",
        "Inj. Normal Saline (500/1000 ml)",
        "Inj. Ringer Lactate (500 ml)",
        "Ipratropium Bromide (20 ml)",
        "IV Cannula 18 No",
        "IV Cannula 20 No",
        "IV Cannula 22 No",
        "IV Cannula 24 No",
        "Lignocaine gel 2% (15 gm)",
        "Nebulizer Mask with tubing (Large)",
        "Neomycin Sulphate 0.5%, bacitracin zinc (250 units per gm, I-cysteine 0.2%, glycine 1%, dl-threonine 0.1% (Cicatrin) Powder 10 gm",
        "Paper Adhesive Tape (1”)",
        "Polymyxin B Sulphate Skin Ointment with lignocaine (20 gm)",
        "Povi-iodine Solution 10% (450 ml)",
        "Silver Sulphadiazine Cream (50gm)",
        "Sterilized Gauze Pieces 10 cm x 10 cm 1 box having 10 packs of 10 pieces",
        "Tab. Angised 0.5 mg",
        "Tab. Captopril 25 mg",
        "Tab. Paracetamol 500 mg",
        "Paper Ream",
        "Expense Register",
        "Vehicle Log Book Fuel for vehicle meter reading",
        "Stock Register",
        "Dispatch Register",
        "Diary Register",
        "File Cover A4",
        "Indent Book for Store",
        "Emergency Medical Kit Bags for Rescue Posts (RP’s)",
        "Emergency Backpack",
        "Dead Body Sheets",
        "Wooden Splints (Small 3\"x18)",
        "Wooden Splints (Medium 3\"x36\")",
        "Rescue Working Gloves 10\"",
        "Alcohol Swab (200 No/Box)",
        "Duster Cloth",
        "Detergent powder (1 Kg) pack",
        "Hand Wash Soap",
        "Surface cleaner",
        "AFFF"
    )

    val sskMedicineList = listOf(
        "Tab. Paracetamol 500 mg",
        "Tab. Angised 0.5 mg",
        "Inj. Hydrocortisone (250 mg)",
        "Ipratropium Bromide (20 ml)",
        "Inj. Dimenhydrinate (50 mg / ml)",
        "Inj. 25% Dextrose Water (20 ml)",
        "Tab. Captopril 25 mg",
        "Inj. Ringer Lactate (500 ml)",
        "Inj. Normal Saline (500/1000 ml)",
        "Inj. Diclofenac sodium water based",
        "Povi-iodine Solution 10% (450 ml)",
        "Polymyxin B Sulphate Skin Ointment with lignocaine (20 gm)",
        "Lignocaine gel 2% (15 gm)",
        "Silver Sulphadiazine Cream (50gm)",
        "Alcohol Swabs",
        "Disposable Syringes 05 ml",
        "Disposable 20 ml",
        "IV Cannula 18 No",
        "IV Cannula 20 No",
        "IV Cannula 22 No",
        "IV Cannula 24 No",
        "Drip Set",
        "Cotton Bandages BPC 6.5 cm X 6 meter",
        "Cotton Bandages BPC 10 cm X 6 meter",
        "Cotton Bandages BPC 15 cm X 6 meter",
        "Crape Bandage Size 04 inches x 4.5 meter",
        "Sterilized Gauze Pieces 10 cm x 10 cm 1 box having 10 packs of 10 pieces",
        "Paper Adhesive Tape (1\")",
        "Cotton Roll (500 gm)",
        "Nebulizer Mask with tubing (Large)",
        "Cervical Collar with chin Support",
        "Compatible Lancets",
        "Glucometer Strips Accu-Check Active",
        "Glucometer Strips Accu-Check Instant",
        "Glucometer Strips Accu-Check Performa",
        "Glucometer Strips Medisign",
        "Neomycin Sulphate 0.5%, bacitracin zinc",
        "Burn Cream",
        "Disposable Latex Gloves (in pairs)"
    )

    val sskExportOrder = listOf(
        "Tab. Paracetamol 500 mg",
        "Tab. Angised 0.5 mg",
        "Inj. Hydrocortisone (250 mg)",
        "Ipratropium Bromide (20 ml)",
        "Inj. Dimenhydrinate (50 mg / ml)",
        "Inj. 25% Dextrose Water (20 ml)",
        "Tab. Captopril 25 mg",
        "Inj. Ringer Lactate (500 ml)",
        "Inj. Normal Saline (500/1000 ml)",
        "Inj. Diclofenac sodium water based (75 mg / 3ml)",
        "Povi-iodine Solution 10% (450 ml)",
        "Polymyxin B Sulphate Skin Ointment with lignocaine (20 gm)",
        "Lignocaine gel 2% (15 gm)",
        "Silver Sulphadiazine Cream (50gm)",
        "Alcohol Swabs",
        "Disposable Syringes 05 ml",
        "Disposable 20 ml",
        "IV Cannula 18 No",
        "IV Cannula 20 No",
        "IV Cannula 22 No",
        "IV Cannula 24 No",
        "Drip Set",
        "Cotton Bandages BPC 6.5 cm X 6 meter (2.5 inch)",
        "Cotton Bandages BPC 10 cm X 6 meter (4 inch)",
        "Cotton Bandages BPC 15 cm X 6 meter",
        "Crape Bandage Size 04 inches x 4.5 meter",
        "Sterilized Gauze Pieces 10 cm x 10 cm 1 box",
        "Paper Adhesive Tape (1”)",
        "Cotton Roll (500 gm)",
        "Nebulizer Mask with tubing (Large)",
        "Adjustable Hard Cervical Collar with chin Support",
        "Compatible Lancets",
        "Glucometer Strips Accu-Check Active",
        "Glucometer Strips Accu-Check Instant",
        "Glucometer Strips Accu-Check Performa",
        "Glucometer Strips Medisign",
        "Neomycin Sulphate 0.5%, bacitracin zinc",
        "Burn Cream",
        "Examination Gloves"
    )

    val specialDecimalMeds = setOf(
        "Ipratropium Bromide (20 ml)",
        "Inj. Normal Saline (500/1000 ml)",
        "Inj. Ringer Lactate (500 ml)",
        "Povi-iodine Solution 10% (450 ml)",
        "Polymyxin B Sulphate Skin Ointment with lignocaine (20 gm)",
        "Lignocaine gel 2% (15 gm)",
        "Surface Disinfectant Spray",
        "Ethyl Chloride Spray (175 ml)",
        "Silver Sulphadiazine Cream (50gm)",
        "Paper Adhesive Tape (1”)",
        "Cotton Roll (500 gm)",
        "Neomycin Sulphate 0.5%, bacitracin zinc"
    )
}