package com.epicx.apps.dailyconsumptionformapp

object FormConstants {
    val vehicleList = listOf(
        "BNA 07", "BNA 08", "BNA 09", "BNA 10", "BNA 11", "BNA 17", "BNA 21", "BNA 22",
        "BNA 25", "BNA 26", "BNA 29", "RS-01"
    ) + (1..50).map { n -> "BNB %02d".format(n) }

    val newMedicineList = listOf(
        "Tab. Paracetamol 500 mg",
        "Tab. Asprin 300 mg",
        "Tab. Angised 0.5 mg",
        "Inj. Hydrocortisone (250 mg)",
        "Inj. Pheniramine Maleate (25 mg)",
        "Ipratropium Bromide (20 ml)",
        "Inj. Dimenhydrinate (50 mg / ml)",
        "Inj. 25% Dextrose Water (20 ml)",
        "Inj. Diazepam 10 mg",
        "Tab. Captopril 25 mg",
        "Inj. Ringer Lactate (500 ml)",
        "Inj. Normal Saline (500/1000 ml)",
        "Inj. Diclofenac sodium water based (75 mg / 3ml)",
        "Povi-iodine Solution 10% (450 ml)",
        "Polymyxin B Sulphate Skin (20 gm)",
        "Lignocaine gel 2% (15 gm)",
        "Surface Disinfectant Spray",
        "Ethyl Chloride Spray (175 ml)",
        "Silver Sulphadiazine Cream (50gm)",
        "Airway 0",
        "Airway 1",
        "Airway 2",
        "Airway 3",
        "Airway 4",
        "Airway 5",
        "Laryngeal Mask Airway (LMA) 02",
        "Laryngeal Mask Airway (LMA) 03",
        "Laryngeal Mask Airway (LMA) 04",
        "Alcohol Swabs",
        "Disposable Syringes 05 ml",
        "Disposable 20 ml",
        "IV Cannula 18 No",
        "IV Cannula 20 No",
        "IV Cannula 22 No",
        "IV Cannula 24 No",
        "Drip Set",
        "Intraosseous Needle",
        "Cotton Bandages BPC 6.5 cm X 6 meter (2.5 inch)",
        "Cotton Bandages BPC 10 cm X 6 meter (4 inch)",
        "Cotton Bandages BPC 15 cm X 6 meter",
        "Crape Bandage Size 04 inches x 4.5 meter",
        "Sterilized Gauze Pieces 10 cm x 10 cm 1 box",
        "Paper Adhesive Tape (1”)",
        "Cotton Roll (500 gm)",
        "Nelton Catheter (18 Gauge)",
        "Nebulizer Mask with tubing (Small)",
        "Nebulizer Mask with tubing (Large)",
        "Adjustable Hard Cervical Collar with chin Support",
        "Triangular Bandage (Medium)",
        "Triangular Bandage (Large)",
        "Compatible Lancets",
        "Glucometer Active",
        "Glucometer Strips Accu-Check Active",
        "Glucometer Strips Accu-Check Instant",
        "Glucometer Strips Accu-Check Performa",
        "Glucometer Strips Medisign",
        "Neomycin Sulphate 0.5%",
        "Examination Gloves",
        "Dead Body Sheets",
        "Wooden Splints (Medium 3\"x36\")",
        "Wooden Splints (Small 3\"x18)"
    )

    val sskExportOrder = listOf(
        "Tab. Paracetamol 500 mg",
        "Tab. Angised 0.5 mg",
        "Inj. Hydrocortisone (250 mg)",
        "Ipratropium Bromide (20 ml)",
        "Inj. Dimenhydrinate (50 mg / ml)",
        "Inj. 25% Dextrose Water (20 ml)",
        "Tab. Captopril 25 mg",
        "Inj. Ringer Lactate (500 ml)",
        "Inj. Normal Saline (500/1000 ml)",
        "Inj. Diclofenac sodium water based (75 mg / 3ml)",
        "Povi-iodine Solution 10% (450 ml)",
        "Polymyxin B Sulphate Skin Ointment with lignocaine (20 gm)",
        "Lignocaine gel 2% (15 gm)",
        "Silver Sulphadiazine Cream (50gm)",
        "Alcohol Swabs",
        "Disposable Syringes 05 ml",
        "Disposable 20 ml",
        "IV Cannula 18 No",
        "IV Cannula 20 No",
        "IV Cannula 22 No",
        "IV Cannula 24 No",
        "Drip Set",
        "Cotton Bandages BPC 6.5 cm X 6 meter (2.5 inch)",
        "Cotton Bandages BPC 10 cm X 6 meter (4 inch)",
        "Cotton Bandages BPC 15 cm X 6 meter",
        "Crape Bandage Size 04 inches x 4.5 meter",
        "Sterilized Gauze Pieces 10 cm x 10 cm 1 box",
        "Paper Adhesive Tape (1”)",
        "Cotton Roll (500 gm)",
        "Nebulizer Mask with tubing (Large)",
        "Adjustable Hard Cervical Collar with chin Support",
        "Compatible Lancets",
        "Glucometer Strips Accu-Check Active",
        "Glucometer Strips Accu-Check Instant",
        "Glucometer Strips Accu-Check Performa",
        "Glucometer Strips Medisign",
        "Neomycin Sulphate 0.5%, bacitracin zinc",
        "Burn Cream",
        "Examination Gloves"
    )

    val monthlyOrderConsumptionList = listOf(
        "Alcohol Swabs",
        "Burn Cream",
        "Adjustable Hard Cervical Collar with chin Support",
        "Compatible Lancets",
        "Cotton Bandages BPC 10 cm X 6 meter (4 inch)",
        "Cotton Bandages BPC 15 cm X 6 meter",
        "Cotton Bandages BPC 6.5 cm X 6 meter (2.5 inch)",
        "Cotton Roll (500 gm)",
        "Crape Bandage Size 04 inches x 4.5 meter",
        "Disposable 20 ml",
        "Examination Gloves",
        "Disposable Syringes 05 ml",
        "Drip Set",
        "Glucometer Strips Accu-Check Active",
        "Glucometer Strips Accu-Check Instant",
        "Glucometer Strips Accu-Check Performa",
        "Glucometer Strips Medisign",
        "Inj. 25% Dextrose Water (20 ml)",
        "Inj. Diclofenac sodium water based (75 mg / 3ml)",
        "Inj. Dimenhydrinate (50 mg / ml)",
        "Inj. Hydrocortisone (250 mg)",
        "Inj. Normal Saline (500/1000 ml)",
        "Inj. Ringer Lactate (500 ml)",
        "Ipratropium Bromide (20 ml)",
        "IV Cannula 18 No",
        "IV Cannula 20 No",
        "IV Cannula 22 No",
        "IV Cannula 24 No",
        "Lignocaine gel 2% (15 gm)",
        "Nebulizer Mask with tubing (Large)",
        "Neomycin Sulphate 0.5%, bacitracin zinc",
        "Paper Adhesive Tape (1”)",
        "Polymyxin B Sulphate Skin Ointment with lignocaine (20 gm)",
        "Povi-iodine Solution 10% (450 ml)",
        "Silver Sulphadiazine Cream (50gm)",
        "Sterilized Gauze Pieces 10 cm x 10 cm 1 box",
        "Tab. Angised 0.5 mg",
        "Tab. Captopril 25 mg",
        "Tab. Paracetamol 500 mg",
        "Paper Ream",
        "Expense Register",
        "Vehicle Log Book Fuel for vehicle meter reading",
        "Stock Register",
        "Dispatch Register",
        "Diary Register",
        "File Cover A4",
        "Indent Book for Store",
        "Emergency Medical Kit Bags for Rescue Posts (RP’s)",
        "Emergency Backpack",
        "Dead Body Sheets",
        "Wooden Splints (Small 3\"x18)",
        "Wooden Splints (Medium 3\"x36\")",
        "Rescue Working Gloves 10\"",
        "Alcohol Swab (200 No/Box)",
        "Duster Cloth",
        "Detergent powder (1 Kg) pack",
        "Hand Wash Soap",
        "Surface cleaner",
        "AFFF"
    )

    val rs01MonthlyConsumptionList = listOf(
        "Adjustable Hard Cervical Collar with chin Support",
        "Airway 0",
        "Airway 1",
        "Airway 2",
        "Airway 3",
        "Airway 4",
        "Airway 5",
        "Alcohol Swabs",
        "Compatible Lancets",
        "Cotton Bandages BPC 10 cm X 6 meter",
        "Cotton Bandages BPC 15 cm X 6 meter",
        "Cotton Bandages BPC 6.5 cm X 6 meter",
        "Cotton Roll (500 gm)",
        "Crape Bandage Size 04 inches x 4.5 meter",
        "Delivery Kit",
        "Disposable 20 ml",
        "Disposable Syringes 05 ml",
        "Drip Set",
        "Ethyl Chloride Spray (175 ml)",
        "Face mask (Disposable, Cup shape with double strings)",
        "Glucometer Active",
        "Glucometer Strips Accu-Check Active",
        "Glucometer Strips Accu-Check Instant",
        "Glucometer Strips Accu-Check Performa",
        "Glucometer Strips Medisign",
        "Inj. 25% Dextrose Water (20 ml)",
        "Inj. Adrenaline in Pre-filled Syringe",
        "Inj. Diazepam 10 mg",
        "Inj. Diclofenac sodium water based (75 mg / 3ml)",
        "Inj. Dimenhydrinate (50 mg / ml)",
        "Inj. Hydrocortisone (250 mg)",
        "Inj. Normal Saline (500/1000 ml)",
        "Inj. Paracetamol 60 mg (Water based)",
        "Inj. Pheniramine Maleate (25 mg)",
        "Inj. Ringer Lactate (500 ml)",
        "Intraosseous Needle",
        "Ipratropium Bromide (20 ml)",
        "IV Cannula 18 No",
        "IV Cannula 20 No",
        "IV Cannula 22 No",
        "IV Cannula 24 No",
        "Laryngeal Mask Airway (LMA) 01",
        "Laryngeal Mask Airway (LMA) 02",
        "Laryngeal Mask Airway (LMA) 03",
        "Laryngeal Mask Airway (LMA) 04",
        "Laryngeal Mask Airway (LMA) 05",
        "Lignocaine gel 2% (15 gm)",
        "Nebulizer Mask with tubing (Large)",
        "Nebulizer Mask with tubing (Small)",
        "Nelton Catheter (18 Gauge)",
        "Neomycin Sulphate",
        "Paper Adhesive Tape (1”)",
        "Polymyxin B Sulphate Skin Ointment with lignocaine (20 gm)",
        "Povi-iodine Solution 10% (450 ml)",
        "Silver Sulphadiazine Cream (50gm)",
        "Sterilized Gauze Pieces 10 cm x 10 cm 1 box having 10 packs of 10 pieces",
        "Surface Disinfectant Spray",
        "Tab. Angised 0.5 mg",
        "Tab. Asprin 300 mg",
        "Tab. Captopril 25 mg",
        "Tab. Paracetamol 500 mg",
        "Triangular Bandage (Large)",
        "Triangular Bandage (Medium)",
        "BLS and Fire Orientation Certificate",
        "BLS Certificate",
        "CADRE Certificate",
        "CADRE/ Community Training Note Book for Trainers",
        "Diary Register",
        "Dispatch Register",
        "Emergency Info. Operations Register for Control Room",
        "Emergency Response Form (Duplicate)",
        "Expense Register",
        "File Cover A4",
        "File Cover Legal Size",
        "Fire Incident Reporting Form in No",
        "Info Register",
        "Fuel Log Book",
        "Indent Book for Store",
        "PTS Referral Form in Pad",
        "Rescue Scout Form Mohafiz in Pad",
        "Stock Register",
        "Trauma Registration Form in Pad",
        "Vehicle Log Book Fuel for vehicle meter reading",
        "Vehicle Log Register for Rescue Stations",
        "Vehicle Repair & Maintenance Log Book (140 Leaves) Landscape",
        "Vehicle Repair & Maintenance Register for TMI",
        "Paper Reams A4 Fine 80gm (500 sheets per Ream)",
        "Printer Toner Hp 1006 (35A)",
        "Printer Toner Hp 2035 (05A) /2055",
        "Printer Toner Hp 102A (17A)",
        "Printer Toner Hp 12A (79A)",
        "Printer Toner M6500NW Pantum",
        "Printer Toner BP5100DW Pantum",
        "Photocopier Toner XEROX B1025 / B1022 MFP",
        "Printer Toner P3005 (51A)",
        "Printer Toner HP203DW (30A)",
        "Printer Toner (135A/107A)",
        "Printer Toner 44A (MFP,28-31)",
        "Printer Toner Hp 1320 (49A)",
        "Printer Toner Hp 1102 (85A)",
        "Printer Toner Hp PRO 400 M401 Duplex (80A)",
        "Printer Toner Hp PRO 402DN (26A)",
        "Printer Toner Hp(13A)",
        "Printer Toner Hp(83A)",
        "Printer Toner Hp 1606 (78A)",
        "Printer Toner Cannon LBP 2900",
        "Printer Toner Ricoh 3510/3500",
        "Printer Toner Cannon LBP 6300 DN",
        "Color Printer Toner HP LaserJet Pro M255dw",
        "Printer Toner HP 4350N",
        "Printer Toner HP 4200DN",
        "Printer Toner HP Laser Jet (P2014)",
        "Printer Toner Hp 404DN (76A)",
        "Printer Toner Hp 90X",
        "Color Printer Toner HP MFP M479 FNW",
        "Color Printer Toner MFP M281 FDW (203A)",
        "Color Printer Toner 150A/117A",
        "AFFF (Litters)",
        "Bath Soap",
        "Caution Tape Roll (For Incidents)",
        "Dead Body Sheets",
        "Dettol Liquid 1 Liter Bottle",
        "Disposable Latex / Examination Gloves (Large Size)",
        "Dust Mop Complete",
        "Dust Mop Refill",
        "Dustbin Large with wheels",
        "Dustbin Small",
        "Duster Cloth",
        "Emergency Backpack",
        "Emergency Medical Kit Bags for Rescue Posts (RP’s)",
        "Examination Gloves",
        "Face/ dust mask (50 No/Box)",
        "Floor Cleaner liquid",
        "Hand wash Soap",
        "Leather Gloves 16\"",
        "Phenyl Bottle",
        "Rescue Working Gloves 10\"",
        "Standing Broom",
        "Surf Pack (1 Kg) pack",
        "Sweep Bottle",
        "Tissue Box",
        "Toilet Cleaner Brush",
        "Wet Mop Complete",
        "Wet Mop Refill",
        "Wiper",
        "Wooden Splints (Large 3\"x 54\")",
        "Wooden Splints (Medium 3\"x36\")",
        "Wooden Splints (Small 3\"x18)",
        "Barret Cap",
        "Belt with buckle",
        "Community Reflecting Vests",
        "Reflecting Vests",
        "Rescue Jacket",
        "Rescue Polo Shirts",
        "Rescue Summar Shirts",
        "Rescue T-Shirt",
        "Rescue Uniform",
        "Safety Helmet",
        "Safety Shoes"
    )
}